#!/usr/bin/env bash
set -euo pipefail

export GOCACHE="${GOCACHE:-/tmp/go-cache}"

target_os=${1:-$(go env GOOS)}
target_arch=${2:-$(go env GOARCH)}

echo "building backend for OS: ${target_os}, Arch: ${target_arch}"
CGO_ENABLED=0 GOOS=${target_os} GOARCH=${target_arch} go build \
  -ldflags '-extldflags "-static"' \
  -o ./build/fusion \
  ./cmd/server
